hackerwins/codepair-old

- netlify.toml
Fix a 404 error when accessing the subpath.
> Add redirects for all paths

- package-lock.json
- package.json
- src/App.tsx
Use HashRouter to avoid 404 error on browser refresh in gh-pages.
https://medium.com/@bennirus/deploying-a-create-react-app-with-routing-to-github-pages-f386b6ce84c2
> Add `deploy` command to publish to gh-pages

- docker/docker-compose.yml
- docker/envoy.Dockerfile
- docker/envoy.yaml
- docker/yorkie.json
We need docker files to run without cloning [yorkie-js-sdk](https://github.com/yorkie-team/yorkie-js-sdk).
> Add docker files

- .prettierrc.js
- src/App.tsx
- src/actions/docActions.ts
- src/components/Editor/CodeEditor.tsx
- src/components/NavBar.tsx
- src/index.css
- src/pages/DocPage.tsx
- src/reducers/docReducer.ts
> Update prettier printWidth 120

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/PULL_REQUEST_TEMPLATE.md
via #23 
Please tell me if you need more information😀
> Add github template

- .eslintignore
- .eslintrc.json
- .gitignore
- package-lock.json
- package.json
- src/App.tsx
- src/actions/docActions.ts
- src/actions/peerActions.ts
- src/components/Editor/ClientCursor.ts
- src/components/Editor/CodeEditor.tsx
- src/pages/DocPage.tsx
- src/reducers/docReducer.ts
- src/reducers/peerReducer.ts
- src/store/store.ts
- tsconfig.json
What does this PR do?
Apply eslint
What are the relevant tickets?
#14
> Apply eslint

- src/components/Modal/index.tsx
Add common model component
like leetcode setup screen
The actual content will be delivered to children
> Add common modal component

- src/App.test.tsx
- src/App.tsx
- src/components/Editor/CodeEditor.tsx
- src/index.tsx
- src/pages/DocPage.tsx
- src/reducers/docReducer.ts
- src/reducers/peerReducer.ts
- src/store/store.ts
- tsconfig.json
This will help VSCode and other IDE to resolve path in TypeScript
https://create-react-app.dev/docs/importing-a-component/#absolute-imports
Fixes #
> Add baseUrl and paths in tsconfig.json

- package.json
Before code commit, check eslint
Fixes #21
> Add pre-commit eslint

- .eslintrc.json
- src/components/Editor/CodeEditor.tsx
A bug occurs because the loop ends while it is running.
This loop has to be traversed all the way to the end.
> Fix a bug that peers disconnect

- docker/docker-compose.yml
- package-lock.json
- package.json
I think codepair is a service, so it looks good to fix the version
> Fix yorkie version 0.1.0

- src/components/Editor/CodeEditor.tsx
after [this commit](https://github.com/yorkie-team/yorkie-js-sdk/pull/123), changed event info
Fixes #
> change client event peers-changed

- src/components/Editor/CodeEditor.tsx
- src/components/Editor/CodeNavBar.tsx
- src/components/NavBar.tsx
- src/pages/DocPage.tsx
- src/reducers/rootReducer.ts
- src/reducers/settingReducer.ts
user can select their code mode
Fixes #11
> Add user edit setting on codemode

- src/components/Editor/CodeEditor.tsx
- src/components/Editor/CodeNavBar.tsx
- src/components/Editor/CodeSetting.tsx
- src/reducers/settingReducer.ts
User can edit keymap, theme, tabsize
Fixes #11
> Add edit function keymap, theme, tabsize

- src/features/settingSlices.ts
- src/utils/storage.ts
Apply localstorage to saving user setting
First, I have implemented only the simplest function
Let me know if you have any additional comments🙇
Fixes #11
> Apply localstorage to saving user setting

- src/components/Editor/Cursor.ts
- src/components/Editor/index.tsx
- src/features/docSlices.ts
Change the order of client sync call
Fixes #36
> Change the order of client sync call

- src/components/Editor/Cursor.ts
- src/components/Editor/editor.css
- src/components/Editor/index.tsx
Show the username on the cursor.
Fixes #
> Display username on cursor

- src/components/Editor/CodeEditor/index.tsx
- src/components/Editor/index.tsx
- src/components/Toolbar/index.tsx
- src/features/docSlices.ts
Replace PlainText with Markdown.
Markdown is more useful as people often write down text and code together during coding interviews.
Fixes #
> Replace PlainText with Markdown

- src/components/Editor/Board/Canvas/Container.ts
- src/components/Editor/Board/Canvas/line.ts
If there is only one point, there is an error case
Remove drawEraserLine and use existing draw function
Fixes #59
> When deleting a line, a script error occurs in the remote clients

- src/components/Editor/Board/Canvas/Container.ts
- src/components/Editor/Board/Canvas/Shape.ts
- src/components/Editor/Board/Canvas/worker.ts
- src/components/Editor/CodeEditor/index.tsx
- src/features/docSlices.ts
Apply type parameter.
Yorkie JS SDK started to provide [a type parameter to Document](https://github.com/yorkie-team/yorkie-js-sdk/pull/148).
We can strictly check the type by specifying the type parameter for CodePair document.
@ppeeou May I ask you to clean up the remaining types in `Shape.ts`?
Fixes #
> Apply type parameter

- src/components/Editor/index.tsx
- src/components/NavBar/NetworkButton.tsx
- src/components/NavBar/ShareButton.tsx
- src/components/NavBar/index.tsx
- src/components/commons/Popover.tsx
- src/features/docSlices.ts
Display network status to the user 
users can know that they can save a document even when offline.
Fixes #75
> Display network status

- src/components/Editor/Sidebar/LineButton.tsx
The buttom location has changed since the PR below
https://github.com/yorkie-team/yorkie-codepair/pull/95
Fixes #98
> Adjust brush button postion

- package.json
- src/app/App.test.tsx
- src/utils/eventDispatcher.test.ts
- src/utils/storage.test.ts
Add test case of util function
Fixes #91
> Add utils testcase

- package-lock.json
- package.json
- src/components/Editor/CodeEditor/index.tsx
- src/components/Editor/index.tsx
- src/components/Toolbar/index.tsx
- src/features/docSlices.ts
`yorkie-js-sdk` 0.1.4 has been released, so it applies to Codepair.
Fixes #
> Update yorkie-js-sdk 0.1.4

- src/components/Editor/DrawingBoard/Canvas/Worker/EraserWorker.ts
Modified to be able to erase small dots with an eraser
1. crosswise elimination method(now)
2. range check from the point(will provide)
Fixes #106
> Adding a method of erasing lines

- src/components/Editor/DrawingBoard/Canvas/Worker/EraserWorker.ts
- src/components/Editor/DrawingBoard/Canvas/Worker/LineWorker.ts
- src/components/Editor/DrawingBoard/Canvas/Worker/RectWorker.ts
- src/components/Editor/DrawingBoard/Canvas/Worker/SelectorWorker.ts
- src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts
Wrap yorkie doc update function with try-catch
why?
When using  `deleteByID` `getElementByID`, an error occurs if the node has been deleted by GC.
Fixes #77
>  Wrap doc update function with try-catch

- webapp/src/index.tsx
we don't need to use sentry in development version.
Fixes #
> Change to use sentry only for production version

- webapp/src/components/Editor/DrawingBoard/Canvas/Board.ts
- webapp/src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts
- webapp/src/components/Editor/DrawingBoard/index.tsx
- webapp/src/components/Editor/Sidebar/index.tsx
- webapp/src/features/boardSlices.ts
Add feature to erase all shapes on the drawing board
Fixes #123
> Feature to clear all shapes on drawing board

- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/Editor/DrawingBoard/Canvas/Worker/RectWorker.ts
- webapp/src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts
update yorkie sdk version 0.1.6
https://github.com/yorkie-team/yorkie-js-sdk/releases/tag/v0.1.6
Fixes #
> Update yorkie sdk version 0.1.6

- webapp/src/components/NavBar/index.tsx
Create a new document when clicking the logo on GNB
Fixes #
> Create a new document when clicking the logo on GNB(#133)

- docker/envoy.Dockerfile
- docker/envoy.yaml
- Update envoy version to 1.19.0
See yorkie-team/yorkie-js-sdk#227 and yorkie-team/yorkie-js-sdk#234
Fixes #134
> feat: update envoy to 1.19.0

- .dockerignore
- README.md
- docker/docker-compose.dev.yml
- webapp/Dockerfile
- webapp/package-lock.json
- webapp/package.json
To create a consistent development environment
None
Fixes #137
> Add Dockerfile and Docker compose configuration

- webapp/.npmrc
- webapp/package-lock.json
- webapp/package.json
Check development environment and make package consistent.
#144 #137
Fixes #151
> Check development environment (#151)

- webapp/src/components/Editor/CodeEditor/index.tsx
Prevent initial content ​​from being removed by undo
Fixes #186
> Prevent initial content ​​from being removed by undo

- docker/docker-compose.yml
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/Editor/DrawingBoard/index.tsx
- webapp/src/features/docSlices.ts
change interface name to apply : https://github.com/yorkie-team/yorkie-js-sdk/commit/47478e73a91634c15055adb1dfc0977e8656a5f0
Fixes #
> apply yorkie-js-sdk v0.2.8

- package-lock.json
- package.json
- src/components/Editor/CodeEditor/index.tsx
* support presentation view 
* This use marpit library.
Fixes #
> support  slide preview

- src/features/settingSlices.ts
If the user's system is dark, the editor theme is dark when user first visited
Fixes #214
> Respect system theme

- package-lock.json
- package.json
Uninstall `@types/redux` package.
﻿﻿﻿Redux contains built-in TypeScript declarations
> Redux contains built-in TypeScript declarations

- src/components/Editor/DrawingBoard/Canvas/Board.ts
- src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts
- This fixes the error of presence shapes not being drawn when multiple users are participating
Fixes #
> Fix error of presence shapes not being drawn when multiple users are participating

- MAINTAINING.md
- docker/docker-compose.yml
- package-lock.json
- package.json
Bump up Yorkie to 0.3.0
Fixes #
> Bump up Yorkie to 0.3.0

- MAINTAINING.md
- docker/docker-compose.yml
- package-lock.json
- package.json
- src/components/Editor/CodeEditor/index.tsx
- src/features/docSlices.ts
Bump up Yorkie to 0.3.2
Fixes #
> Bump up Yorkie to 0.3.2

- src/components/Editor/CodeEditor/index.tsx
When clicking a link in Markdown, I made it so that a new window opens when clicking with metaKey.
* `mac` is  ⌘ `command` key 
* `window` is ⊞ `window` key
https://user-images.githubusercontent.com/591983/223676153-bafe1d1b-0dfc-4e48-97bc-c03373180a47.mov
Fixes #
> add link feature when link is clicked with meta  key

- src/components/Editor/DrawingBoard/Canvas/line.ts
Prevents lines from disappearing when drawn short.
Fixes #
> fix wrong line drawing

- src/components/SideBar/index.tsx
- src/features/linkSlices.ts
- src/pages/DocPage.tsx
Fixes an issue with the heading not getting imported properly after adding a new link to a group.
There are two problems with this
* Suppresses selected status in the list
* Don't rename links when the title changes
Fixes #
> fix bad file links when link is created

- src/app/App.tsx
- src/components/Editor/CodeEditor/index.tsx
Adjust the scroll position to top when clicking head.
Fixes #
> fixed scroll position when head is clicked

- docker/docker-compose.yml
- package-lock.json
- package.json
- src/components/Editor/DrawingBoard/index.tsx
- src/components/Editor/index.tsx
- src/features/peerSlices.ts
Bump up Yorkie to v0.3.3
Fixes #
> Bump up Yorkie to v0.3.3

- src/components/Editor/Sidebar/Settings.tsx
- src/components/Editor/mime/text/md/Editor.tsx
- src/components/NavBar/PageButton.tsx
- src/components/SideBar/LinkTreeView.tsx
- src/components/SideBar/SidebarItem.tsx
- src/components/SideBar/WorkspaceButton.tsx
- src/features/linkSlices.ts
- src/features/settingSlices.ts
- src/pages/DocPage.tsx
- src/pages/NewPage.tsx
- src/utils/document.ts
* implement date filter (last day, last month, last week) 
Fixes #
> support date filter

- package-lock.json
- package.json
- src/components/Editor/mime/application/whiteboard/Editor.tsx
- src/components/Editor/mime/text/md/CodeEditor/MiniDraw.scss
- src/components/Editor/mime/text/md/CodeEditor/MiniDraw.tsx
- src/components/Editor/mime/text/md/CodeEditor/codemirror/markdown-fold.ts
- src/components/Editor/mime/text/md/CodeEditor/codemirror/tldraw-preview.ts
- src/components/Editor/mime/text/md/CodeEditor/index.tsx
- src/index.scss
* support tldraw editor in markdown 
https://user-images.githubusercontent.com/591983/235969379-aa32ebb9-e4d6-4dd2-b964-531f595f86ad.mov
Fixes #
> support tldraw editor in markdown

- docker/docker-compose.yml
- package-lock.json
- package.json
- src/components/Editor/mime/text/md/CodeEditor/index.tsx
Bump up Yorkie to 0.4.1.
Fixes #
> Bump up Yorkie to 0.4.1

- docker/docker-compose.yml
- package-lock.json
- package.json
Bump up Yorkie to 0.4.2.
Fixes #
> Bump up Yorkie to 0.4.2

- package-lock.json
- package.json
Bump up Yorkie to v0.4.13
Fixes #
> Bump up Yorkie to v0.4.13

- package-lock.json
- package.json
- src/components/Editor/index.tsx
- src/components/Editor/mime/text/md/CodeEditor/index.tsx
- src/features/peerSlices.ts
Bump up Yorkie to v0.5.2
Fixes #
> Bump up Yorkie to v0.5.3

- src/components/application/InstantBoard.tsx
- src/pages/PageLayout.tsx
> Show v2 dialog
