hackerwins/codepair-old

.eslintrc.json, src/components/NavBar/ViewItem.tsx, src/components/NavBar/ViewList.tsx, src/components/NavBar/Viewer.tsx, src/components/NavBar/index.tsx, src/components/Popover/index.tsx, src/components/Toolbar/index.tsx, src/hooks/usePeer.ts
User can check the currently connected peers.
we need to merge after this PR.
https://github.com/yorkie-team/yorkie-codepair/pull/37
Fixes #
=> User can check the currently connected peers

docker/docker-compose.yml, src/components/Editor/index.tsx, src/features/docSlices.ts, src/hooks/usePeer.ts
There are cases where the user does not receive `peer-event` when accessing
Thus, the time of document and client creation and server synchronization is divided.
After creating client and document, execute `client.subscribe` and then synchronize with server
as-is
create client,document and  sync server -> subscribe
to-be
create client,document -> subscribe -> sync server
Fixes #
=> Fix peer sync bug

src/components/Editor/index.tsx
=> When an error existed, display first

src/app/rootReducer.ts, src/components/Editor/Board/Canvas/Canvas.ts, src/components/Editor/Board/Canvas/Container.ts, src/components/Editor/Board/Canvas/Shape.ts, src/components/Editor/Board/Canvas/utils.ts, src/components/Editor/Board/Content.tsx, src/components/Editor/Board/Sidebar.tsx, src/components/Editor/Board/index.css, src/components/Editor/Board/index.tsx, src/components/Editor/CodeEditor/index.css, src/components/Editor/CodeEditor/index.tsx, src/components/Editor/index.tsx, src/components/Toolbar/index.tsx, src/features/boardSlices.ts, src/features/docSlices.ts, tsconfig.json
Code editor provides users with drawing tools
Currently, only the line drawing part is provided
-Add board component
-Add function to draw lines on a canvas
Fixes #
=> Add drawing function 

src/components/Editor/Board/Canvas/Container.ts, src/components/Editor/Board/Canvas/Shape.ts, src/components/Editor/Board/Canvas/schedule.ts, src/components/Editor/Board/Canvas/utils.ts
Currently, every time the user moves the mouse point, all points are recorded, so a lot of unnecessary data is stored.
When passing, the accumulated value is reduced and stored through the [douglas-peucker-algorithm](https://cartography-playground.gitlab.io/playgrounds/douglas-peucker-algorithm/)
The following shows the reduced results when applied
points length 
left draw 10: 3185 , right draw 1: 528
points length
left draw 10: 623 , right draw 1: 89
It seems that the average number of stored points reduced to 1/6
douglas-peucker-algorithm
https://cartography-playground.gitlab.io/playgrounds/douglas-peucker-algorithm/
Fixes #48
=> Reduce the value of the stored points by applying the douglas-peucker-algorithm

.eslintrc.json, src/components/Editor/Board/Canvas/Container.ts, src/components/Editor/Board/Canvas/line.ts, src/components/Editor/Board/Canvas/utils.ts, src/components/Editor/Board/Canvas/worker.ts
Separate functions into functions or classes.
what
- Separate functions for line in utils
- Separate document update purposes into worker class
why
Because Container class was working in various ways before,
It separates the two tasks: drawing the canvas and updating the document.
Fixes #
=> Separate document update purposes into worker class

src/components/Editor/Board/Content.tsx
The lines are not visible because they are mild gray in light mode.
After that, we need to be able to choose the color of the line.
Fixes #
=> Bugfix no line is visible in light mode

src/components/Editor/Board/Canvas/Canvas.ts
Supports retina display
as-is
to-be
https://geoexamples.com/d3/2017/10/24/canvas-mapping-with-retina.html
Fixes #50
=> Support retina on canvas

docker/envoy.yaml, package-lock.json, package.json, src/index.tsx
Introduce Sentry for application monitoring.
Fixes #67
=> Introduce Sentry for application monitoring

src/components/Editor/Board/Canvas/Container.ts, src/components/Editor/Board/Canvas/dom.ts, src/components/Editor/Board/index.css, src/components/Editor/Board/index.tsx
Allows drawing on mobile.
Fixes #63
=> Support mobile device

src/components/Editor/Board/Canvas/Container.ts
Firefox, opera, and explore do not support touch event.
Touch values are used only when there is a touch event.
I haven't tested it for all browser versions, but it seems to work with most browsers.
Fixes #73
=> Bugfix a bug TouchEvent is not defined on canvas

package-lock.json, package.json, src/index.tsx
Set up release tracking.
Fixes #72
=> Set up release tracking

src/app/App.tsx, src/components/Editor/CodeEditor/index.tsx, src/components/NavBar/index.tsx, src/components/Toolbar/Settings.tsx, src/features/settingSlices.ts
Provide the app dark/light mode in settings.
Fixes #58
=> Provide the app dark/light mode in settings

src/components/Editor/CodeEditor/index.tsx, src/components/Editor/Editor.tsx
I thought that if I use `z-index` well, can implement the function.
When doing so, a problem occurs when the `canvas` and `codeEditor` overlap.
So, I used the click event to perform the focus function.
Fixes #80
=> Focus on Code Editor when clicking on an empty space

src/components/Editor/Board/Canvas/utils.ts, src/components/Editor/Board/Canvas/worker.ts
It seems that an error occurs in the part that checks the length during reverse traversal.
First, it will be bypassed and corrected in the direction of straight 
https://github.com/yorkie-team/yorkie-codepair/issues/44#issuecomment-812996079
Fixes #
=> Removes the reverse traversal function, when selected

src/components/Editor/CodeEditor/index.tsx
Add addon comment
Users can use the editor comment toggle function.
Fixes #82
=> Add addon comment on CodeEditor

src/components/Editor/Board/Canvas/Container.ts, src/components/Editor/Board/index.tsx, src/utils/eventDispatcher.ts
Change Selector tool, after creating a controllable shape
Most editors provide the user to create a shape and then immediately change it to the selector tool.
Fixes #
=> Change Selector tool, after creating a controllable shape

src/components/Editor/Board/Canvas/line.ts
After drawing the canvas, call closePath.
why
It may result in a shape that the user did not intend
Fixes #
=> Call closePath, After drawing the shape

src/features/boardSlices.ts
Change the basic color to red
why?
we can see both when in dark mode and when not
Fixes #
=> Set the base color to red

src/components/Editor/Board/Canvas/line.ts
Usually, when modifying the canvas context, context save and restore are used
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/save
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/restore
Fixes #
=> Use save restore, When modifying canvas context

package-lock.json
It looks like the old package-lock file needs to be updated.
Even after npm cache clean and reinstallation, the following error occurred.
```
johyeon:yorkie-codepair johyeon-u$ npm i 
npm WARN tarball tarball data for yorkie-js-sdk@git+ssh://git@github.com/yorkie-team/yorkie-js-sdk.git#c9996019142f404d99e8f0f02a4fd43ab03e3709 (sha512-ZbgHtiViEKzvmX8z0orYt/dvXTPktvLyb9fY1G7x/siKE7kNsPp61MBTIXRkzrDFdCq8YKW/dS3jZrjSu2SYRA==) seems to be corrupted. Trying again.
```
Fixes #
=> Update yorkie-js-sdk 0.1.4 package-lock.json

design/drawing-canvas.md, src/components/Editor/DrawingBoard/Canvas/Board.ts, src/components/Editor/DrawingBoard/Canvas/CanvasWrapper.ts, src/components/Editor/DrawingBoard/Canvas/Worker/EraserWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/LineWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/NoneWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/RectWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/SelectorWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/index.ts, src/components/Editor/DrawingBoard/index.tsx, src/components/Editor/Editor.tsx, src/components/Editor/index.tsx, src/features/docSlices.ts
Separate concerns from `useEffect`
Since Drawing board is updating all in one `useEffect`, a new canvas is created even if the `tool` is changed.
Fixes #
=> Separate concerns from useEffect on drawing board

docker/docker-compose.yml, docker/envoy.yaml
https://github.com/yorkie-team/yorkie-codepair/blob/bb88f445b1a17b7a498b399712cd7bfcf9dcc794/docker/envoy.yaml#L45
It doesn't work setting localhost to connect to a yorkie server on Linux. Although we binded some ports(host:11101 <-> yorkie:11101), envoy container can't connect to the yorkie server with localhost by default on Linux. If you want this, you should define a hostname for `host-gateway` in `extra_hosts` of `docker-compose.yml`.
After that, you can access host by the extra hostname you configured.
Please take a look at the example.
```bash
root@80d7d00775cd:/# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.1      host.docker.internal <- You …
```
=> Add comments to help configure envoy and yorkie containers

webapp/src/components/Editor/CodeEditor/Cursor.ts
Change drag content background color opacity by rgba, not by opacity.
Change drag content background color opacity by rgba, not by opacity. So It made the letters recognizable.
metaData's color is expressed by hex. So I changed it rgba and lower the opacity.
Fixes #127
=> Change drag content background color opacity by rgba

webapp/src/components/Editor/DrawingBoard/Canvas/Board.ts
If mouseup action is performed on mouseout event, unwanted action may occur as shown below.
We didn't create a rectangle, but the selected tool changes.
Distinguish between mouseout event actions and mouseup event actions.
Fixes #
=> Bugfix when mouse out strange work on canvas

webapp/src/components/Editor/CodeEditor/index.scss
Adjust position of vim command that were partially hided.
Add `postion: abosolute; z-index: 2;` for not overlapping `codes`.
|Before adding z-index|After adding z-index|
|:-------:|:-------:|
|![스크린샷 2022-01-24 오후 2 54 14](https://user-images.githubusercontent.com/40482274/150736411-f97819e4-c60b-4ac5-a3be-209c0a4e55ab.png)|![스크린샷 2022-01-24 오후 2 54 06](https://user-images.githubusercontent.com/40482274/150736433-795d9853-bc87-46bc-bf2c-f9c53e616091.png)|
Fixes #148
=> Adjust position of vim command. #148

webapp/src/components/Editor/Editor.tsx
Fix shrinking sidebar when type fully in one line. 
|Before Fix|After Fix|
|:-------:|:-------:|
|![화면 기록 2022-01-28 오후 4 38 22 mov](https://user-images.githubusercontent.com/40482274/151506436-fb48ad57-505b-4601-ac08-2db475a89b1b.gif)|![화면 기록 2022-01-28 오후 4 36 22 mov](https://user-images.githubusercontent.com/40482274/151506306-c72d66ed-4ddc-4c24-9710-28067c1efaa8.gif)|
`flex: 0 0 auto` make editor area not shrink or grow.
Fixes #167
=> Fix sidebar shrinks

docker/docker-compose.yml, package.json, src/components/Editor/CodeEditor/index.tsx
When a client receives a snapshot, `doc.root` is replaced by the snapshot.
It is not detected by the remote change obsever, causing problems with
synchronization.
By adding snapshot event observer to document, value of the editor is
synced and the onChange handler re-setted for the replaced new root.
Fixes https://github.com/yorkie-team/yorkie-js-sdk/issues/347
=> Add snapshot event observer to document

docker/docker-compose.yml, package-lock.json, package.json
Bump up Yorkie to v0.2.15
Address https://github.com/yorkie-team/yorkie/pull/389
=> Bump up Yorkie to v0.2.15

src/components/Editor/CodeEditor/Cursor.ts, src/components/Editor/CodeEditor/index.tsx, src/components/Editor/DrawingBoard/Canvas/Board.ts, src/components/Editor/DrawingBoard/Canvas/Worker/EraserWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/LineWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/RectWorker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts, src/components/Editor/DrawingBoard/Canvas/Worker/index.ts, src/components/Editor/DrawingBoard/Canvas/line.ts, src/components/Editor/DrawingBoard/Canvas/rect.ts, src/components/Editor/DrawingBoard/index.tsx, src/components/NavBar/PeerGroup.tsx, src/components/NavBar/PeerListItem.tsx, src/features/docSlices.ts, src/features/peerSlices.ts
=> Hunkim98 main

src/index.scss
modify tableOfContents panel background color on dark mode 
Fixes #
=> modify tableOfContent panel color when dark mode

src/components/Editor/CodeEditor/index.tsx
Prevent tokens other than headers from coming into the TOC.
Fixes #
=> fixed header check in TOC

src/app/rootReducer.ts, src/components/NavBar/index.tsx, src/components/SideBar/index.tsx, src/features/linkSlices.ts, src/features/navSlices.ts, src/pages/DocPage.tsx
Fixes an issue where data stored in local storage was not synchronized when multiple browser tabs were opened with a Codepair URL.
The storage event is fired on the window when localStorage changes. 
It exclude synchronizing tab information because it changes the way the browser syncs.
Fixes #
=> support localStorage sync

src/components/Editor/index.tsx, src/components/Editor/mime/application/whiteboard/Editor.tsx, src/components/Editor/mime/application/whiteboard/hooks/useMultiPlayerState.ts, src/components/NavBar/NetworkButton.tsx, src/components/NavBar/index.tsx, src/components/SideBar/index.tsx, src/features/docSlices.ts, src/features/linkSlices.ts, src/index.scss, src/pages/DocPage.tsx
* Fixed whiteboard not refreshing 
* Support add button in navbar
* 
Fixes #
=> fixed whiteboard refresh

docker/envoy.yaml, package-lock.json, package.json
Change `yorkie-js-sdk` version to latest for `x-shard-key` exposure
Fixes #
=> Change `yorkie-js-sdk` version to latest for `x-shard-key` exposure

docker/docker-compose.yml, package-lock.json, package.json, src/components/Editor/mime/text/md/CodeEditor/index.tsx, src/features/docSlices.ts
Bump up Yorkie to v0.3.4
Fixes #
=> Bump up Yorkie to v0.3.4

docker/docker-compose.yml, package.json
=> Bump up Yorkie to 0.4.3

src/components/Editor/mime/text/md/CodeEditor/index.tsx
Fixes URL link navigation with fragments not working properly.
In my opinion, when a link contains a fragment in the code mirror, it seems that we cannot retrieve the text including the fragment using `token.string`. However, since the entire link is wrapped in a link-type span element, I have made changes to extract the url from the element, enabling proper navigation to the correct link.
Fixes #248
=> fix to handle links with fragments

src/components/Editor/mime/text/md/CodeEditor/index.tsx
I've removed the 'code' button that was duplicated in the toolbar, alongside the text style option. This was done to address the issue of having the same option twice.
Fixes #
=> Remove duplicated 'code' button from the toolbar
